
import { Dish } from './types';

// Helper to transform the original combo data into the new structure
const transformCombo = (dish: Dish): Dish => {
  if (!dish.category.toLowerCase().includes('combos')) {
    return dish;
  }
  const shortCode = dish.code.split('.')[1] || dish.code;
  const items = dish.name.split('+').map(s => s.trim());
  return {
    ...dish,
    name: shortCode,
    items,
  };
};

const originalMenuData: Dish[] = [
    // Combos
    { code: '144.A1', name: 'Porción de Chaufa c/ Pollo + Pollo Cinco Sabores (dulce)', price: 47.00, category: 'Combos (1 Persona)' },
    { code: '145.A2', name: 'Porción de Chaufa c/ Pollo + Pollo Chi Jau Kay', price: 47.00, category: 'Combos (1 Persona)' },
    { code: '146.A3', name: 'Porción de Chaufa c/ Pollo + Taypá Especial', price: 52.00, category: 'Combos (1 Persona)' },
    { code: '147.A4', name: 'Porción de Chaufa c/ Pollo + Chancho Asado al Ajo', price: 47.00, category: 'Combos (1 Persona)' },
    { code: '148.A5', name: 'Porción de Chaufa c/ Pollo + Tallarín c/ Pollo en Trozos', price: 47.00, category: 'Combos (1 Persona)' },
    { code: '149.A6', name: 'Porción de Chaufa c/ Pollo + Kam Lú Wantán', price: 55.00, category: 'Combos (1 Persona)' },
    { code: '150.B1', name: '1 Sopa Wantán + 1 Pollo en Trozos Saltado c/ Verduras + 2 Porciones de Chaufa c/ Pollo', price: 70.00, category: 'Combos (2 Personas)' },
    { code: '151.B2', name: '1 Sopa Wantán + 1 Chijaukay 2 Sabores + 2 Porciones de Chaufa c/ Pollo', price: 71.00, category: 'Combos (2 Personas)' },
    { code: '152.B3', name: '1/2 Docena de Wantán Frito + 1 Chancho Asado c/ Tamarindo (dulce) + 2 Porciones de Chaufa c/ Pollo', price: 62.00, category: 'Combos (2 Personas)' },
    { code: '153.B4', name: '1/2 Docena de Wantán Frito + 1 Chancho Asado al Ajo + 2 Porciones de Chaufa c/ Pollo', price: 62.00, category: 'Combos (2 Personas)' },
    { code: '154.B5', name: '1/2 Docena de Wantán Frito + 1 Pollo Chijaukay + 2 Porciones de Chaufa c/ Pollo', price: 61.00, category: 'Combos (2 Personas)' },
    { code: '155.B6', name: '1/2 Docena de Sui May + 1 Kam Lu Wantán (dulce) + 2 Porciones de Chaufa c/ Pollo', price: 74.00, category: 'Combos (2 Personas)' },
    { code: '156.C1', name: '1 Sopera Wantán Grande + 1 Chi Jau Kay 2 Sabores + 1 Tallarín c/ Pollo en Trozos + 1 Chaufa c/ Pollo Familiar', price: 127.00, category: 'Combos (3-4 Personas)' },
    { code: '157.C2', name: '1 Sopera Wantán Grande + 1 Chancho Asado c/ Ajos + 1 Kam Lú Wantán (dulce) + 1 Chaufa c/ Pollo Familiar', price: 131.00, category: 'Combos (3-4 Personas)' },
    { code: '158.C3', name: '1 Sopera Wantán Grande + 1 Pollo Enrollado c/ Salsa de Ostión + 1 Chancho Asado c/ Piña (dulce) + 1 Chaufa c/ Pollo Familiar', price: 133.00, category: 'Combos (3-4 Personas)' },
    { code: '159.C4', name: '1 Sopera Wantán Grande + 1 Pollo en Trozos c/ Verduras + 1 Pollo Tipakay (dulce) + 1 Chaufa c/ Pollo Familiar', price: 135.00, category: 'Combos (3-4 Personas)' },
    { code: '150.C5', name: '1 Sopera Wantán Grande + 1 Pollo Limón Kay (agridulce) + 1 Taypá a la Plancha + 1 Chaufa c/ Pollo Familiar', price: 139.00, category: 'Combos (3-4 Personas)' },
    { code: '161.C6', name: '1 Sopera Wantán Especial Grande + 1 Pollo c/ Durazno (dulce) + 1 Tallarín c/ Pollo en Trozos + 1 Chaufa Especial Familiar', price: 148.00, category: 'Combos (3-4 Personas)' },
    { code: '162.C7', name: '1 Sopera Siu Cao Grande + 1 Pollo c/ Piña (dulce) + 1 Tallarín c/ Pollo en Trozos + 1 Chaufa Especial Familiar', price: 149.00, category: 'Combos (3-4 Personas)' },
    { code: '163.C8', name: '1 Docena de Siu May + 1 Tipakay (dulce) + 1 Tallarín Taypá + 1 Chaufa Especial Familiar', price: 150.00, category: 'Combos (3-4 Personas)' },
    { code: '164.C9', name: '1 Sopa Wantán Especial Grande + 1 Kam Lú Wantán (dulce) + 1 Tallarín c/ Pollo en Trozos + 1 Arroz Chaufa Especial Familiar', price: 159.00, category: 'Combos (3-4 Personas)' },
    { code: '165.D1', name: '1 Sopera Wantán Grande + 1 Pollo Cinco Sabores (dulce) + 1 Pollo Enrollado con Espárragos + 1 Chancho Asado con Tausí + 1 Chaufa c/ Pollo Familiar', price: 180.00, category: 'Combos (4-5 Personas)' },
    { code: '166.D2', name: '1 Sopera Wantán Grande + 1 Pollo Chijaukay + 1 Tallarín c/ Pollo en Trozos + 1 Chancho Asado con Tamarindo (dulce) + 1 Chaufa c/ Pollo Familiar', price: 183.00, category: 'Combos (4-5 Personas)' },
    { code: '167.D3', name: '1 Docena de Siu May + 1 Taypá a la Plancha + 1 Kam Lú Wantán (dulce) + 1 Tallarín c/ Pollo en Trozos + 1 Chaufa Especial Familiar', price: 209.00, category: 'Combos (4-5 Personas)' },
    { code: '168.D4', name: '1 Sopa Fuchifú Grande + 1 Tallarín Frito c/ Pollo en Trozos + 1 Kam Lú Wantán (dulce) + 1 Chi Jau Kay + 1 Chaufa c/ Pollo y Chancho', price: 231.00, category: 'Combos (4-5 Personas)' },
    { code: '169.E1', name: '1 Sopera Wantán Grande + 1 Taypá Especial + 1 Carne de Res c/ Frejolito Chino + 1 Ti Pa Kay (dulce) + 1 Chaufa c/ Pollo Familiar', price: 198.00, category: 'Combos (5-6 Personas)' },
    { code: '170.E2', name: '1 Sopa Wantán Especial Grande + 1 Pollo Cuy Pey c/ Piña y Durazno (dulce) + 1 Chancho c/ Frejolito + 1 Tallarín con Pollo en Trozos + 1 Chaufa Especial Familiar', price: 232.00, category: 'Combos (5-6 Personas)' },
    { code: '171.E3', name: '1 Docena de Siu May + 1 Chancho al Ajo + 1 Pollo c/ Almendra + 1 Tallarín de Pollo en Trozos + 1 Tipakay (dulce)', price: 231.00, category: 'Combos (5-6 Personas)' },
    { code: '172.E4', name: '1 Sopa Siu Cao Especial Grande + 1 Pollo Tausí a la Plancha + 1 Tallarín c/ Chancho + 1 Limonkay (agridulce) + 1 Pollo c/ Frejolito + 1 Chaufa Especial Familiar', price: 232.00, category: 'Combos (5-6 Personas)' },
    { code: '173.F1', name: '2 Sopas Wantán Grande + 1 Pollo c/ Champ. y Huevito de Codorniz + 1 Chancho Asado c/ Piña (dulce) + 1 Carne de Res c/ Frejolito + 1 Pollo Limonkay (agridulce) + 1 Taypá Especial + 2 Chaufas c/ Pollo Familiar', price: 272.00, category: 'Combos (7-8 Personas)' },
    { code: '174.F2', name: '2 Sopas Siu Cao Especial Fam. + 1 Pano King Chong Long + 1 Pollo c/ Piña (dulce) + 1 Chancho al Ajo + 1 Tallarín en Trozos Familiar + 1 Taypá Especial + 2 Chaufas Especial Familiar', price: 343.00, category: 'Combos (7-8 Personas)' },
    { code: '175.F3', name: '1 Sopa Siu Cao Especial Familiar + 1 Taypá a la Plancha + 1 Kam Lú Wantán (dulce) + 1 Chi Jau Kay + 1 Tallarín c/ Pollo en Trozos Familiar + 1 Carne con Frejolito + 2 Chaufas Especiales Familiares', price: 358.00, category: 'Combos (7-8 Personas)' },
    { code: '176.G1', name: '2 Sopas Wantán Grande + 1 Chicharrón de Alitas + 1 Pollo a la Fruta (dulce) + 1 Tallarín c/ Pollo en Trozos Familiar + 1 Chancho Asado c/ Ajos + 1 Carne de Res c/ Tausí a la Plancha + 1 Enrollado con Espárragos + 2 Chaufas c/ Pollo Familiar', price: 376.00, category: 'Combos (9-10 Personas)' },
    { code: '177.G2', name: '2 Sopas Wantán Grande + 2 Docenas de Sui Cao Frito + 2 Chicharrones de Pollo + 1 Taypá a la Plancha + 1 Tallarín c/ Pollo en Trozos Familiar + 1 Pollo en Trozos c/ Champiñones + 1 Kam Lú Wantán (dulce) + 1 Carne de Res c/ Tausí + 2 Arroces Chaufas c/ Pollo Familiar', price: 421.00, category: 'Combos (10-12 Personas)' },
    { code: '178.G3', name: '1 Sopa Wantán Grande + 1 Sopa Siu Cao Grande + 1 Docena de Siu Mai + 1 Docena de Primavera + 1 Chi Jau Kay + 1 Pollo c/ Verduras y Champiñones + 1 Tipakay (dulce) + 1 Tallarín Taypá Familiar + 2 Chancho c/ Tausí y Verduras + 2 Chaufas Especial Familiar', price: 467.00, category: 'Combos (10-12 Personas)' },
    { code: '179.H1', name: '2 Sopas Wantán Grande + 2 Docenas de Sui Cao Frito + 2 Lomos c/ Huevo y Champiñones a la cacerola + 1 Tallarín de Pollo en Trozos Familiar + 2 Kam Lú Wantán (dulce) + 2 Chanchos Asados al Ajo + 2 Carnes de Res c/ Tausí a la Plancha + 2 Chaufas de Pollo Familiar', price: 536.00, category: 'Combos (13-14 Personas)' },
    { code: '180.H2', name: '2 Docenas de Siu Mai + 2 Docenas de Enrollado Primavera + 1 Chi Jau Kay + 2 Taypá a la Plancha + 2 Chanchos c/ Tamarindo (dulce) + 2 Pollos Enrollados c/ Salsa de Ostión + 2 Carnes de Res c/ Frejolito + 1 Tallarín c/ Pollo en Trozos Familiar + 2 Chaufas Especial Familiar', price: 596.00, category: 'Combos (13-14 Personas)' },
    { code: '181.H3', name: '3 Sopas Wantán Especiales + 2 Docenas de Siu Mai + 2 Chicharrones de Alita + 2 Kam Lú Wantán (dulce) + 2 Enrollados c/ Espárragos + 2 Carnes de Res c/ Frejolito + 2 Pollos c/ Almendra + 1 Tallarín c/ Pollo en Trozos Familiar + 2 Chaufas Especiales Familiar', price: 645.00, category: 'Combos (13-14 Personas)' },
    // Entradas
    { code: '0401', name: 'Chicharrón de Pollo', price: 28.00, category: 'Entrada', 
      description: 'Crujientes y jugosos trozos de pollo marinados con especias orientales, fritos hasta alcanzar una textura dorada perfecta. Un clásico irresistible para empezar.',
      ingredients: ['Pollo', 'Sillao (Salsa de soja)', 'Kión (Jengibre)', 'Ajo', 'Huevo', 'Chuño (Fécula de papa)']
    },
    { code: '0402', name: 'Chicharrón de Alitas', price: 28.00, category: 'Entrada' },
    { code: '0403', name: 'Siu Mai (1/2 docena)', price: 21.00, category: 'Entrada' },
    { code: '0404', name: 'Jacao (1/2 docena)', price: 21.00, category: 'Entrada' },
    { code: '0405', name: 'Wantán Frito (1/2 docena)', price: 11.00, category: 'Entrada' },
    { code: '0406', name: 'Wantán Frito (1 docena)', price: 19.00, category: 'Entrada' },
    { code: '0407', name: 'Nabo Encurtido', price: 19.00, category: 'Entrada' },
    { code: '0408', name: 'Chancho Asado con Nabo', price: 38.00, category: 'Entrada' },
    { code: '0409', name: 'Pato Asado con Nabo', price: 45.00, category: 'Entrada' },
    { code: '0410', name: 'Rollitos Primavera (1/2 doc.)', price: 21.00, category: 'Entrada' },
    { code: '0411', name: 'Porción de Min Pao (3 unidades)', price: 18.00, category: 'Entrada' },
    { code: '0412', name: 'Siu Cao Frito (1/2 docena)', price: 22.00, category: 'Entrada' },
    { code: '0413', name: 'Mipao Grande', price: 8.00, category: 'Entrada' },
    // Sopas
    { code: '0701', name: 'Sopa Siu Cao', price: 27.00, category: 'Sopas' },
    { code: '0702', name: 'Sopa Siu Cao Especial', price: 30.00, category: 'Sopas' },
    { code: '0703', name: 'Sopa Pac Pow', price: 25.00, category: 'Sopas' },
    { code: '0704', name: 'Sopa Fuchifú', price: 24.00, category: 'Sopas' },
    { code: '0705', name: 'Sopa de Pato con Kión', price: 30.00, category: 'Sopas' },
    { code: '0706', name: 'Sopa Wantán', price: 22.00, category: 'Sopas',
      description: 'Una reconfortante sopa con un caldo de pollo profundo y sabroso, acompañada de finas láminas de pollo, col china y nuestros delicados wantanes rellenos de carne.',
      ingredients: ['Wantanes (relleno de cerdo/pollo)', 'Caldo de pollo', 'Pollo en láminas', 'Col china', 'Cebolla china']
    },
    { code: '0707', name: 'Sopa Wantán Especial', price: 30.00, category: 'Sopas' },
    { code: '0708', name: 'Sopa Wantán c/ Kión', price: 23.00, category: 'Sopas' },
    { code: '0709', name: 'Sopa Womín c/ Pollo y Verd.', price: 24.00, category: 'Sopas' },
    { code: '0710', name: 'Sopa Wantán c/ Huevito y Pollo', price: 25.00, category: 'Sopas' },
    { code: '0711', name: 'Sopa de Pollo y Fensi', price: 24.00, category: 'Sopas' },
    { code: '0712', name: 'Sopa Womín', price: 22.00, category: 'Sopas' },
    { code: '0713', name: 'Sopa Womín Especial', price: 27.00, category: 'Sopas' },
    // Tallarines
    { code: '1301', name: 'Tallarín Taypá', price: 39.00, category: 'Tallarines' },
    { code: '1302', name: 'Tallarín c/ Pollo en Trozos y Lang.', price: 43.00, category: 'Tallarines' },
    { code: '1303', name: 'Tallarín Sam Sí', price: 43.00, category: 'Tallarines' },
    { code: '1304', name: 'Tallarín con Chancho Asado', price: 29.00, category: 'Tallarines' },
    { code: '1305', name: 'Tallarín con Langostinos', price: 38.00, category: 'Tallarines' },
    { code: '1306', name: 'Tallarín con Carne de Res', price: 29.00, category: 'Tallarines' },
    { code: '1307', name: 'Tallarín c/ Huevitos de Codorniz y Champiñones', price: 30.00, category: 'Tallarines' },
    { code: '1308', name: 'Tallarín c/ Huevitos de Cord. y Taufú', price: 31.00, category: 'Tallarines' },
    { code: '1309', name: 'Tallarín con Verdura y Taufú', price: 27.00, category: 'Tallarines' },
    { code: '1310', name: 'Tallarín con Pollo y Chancho', price: 32.00, category: 'Tallarines' },
    { code: '1311', name: 'Tallarín Especial', price: 30.00, category: 'Tallarines' },
    { code: '1312', name: 'Tallarín c/ Taufú y Champiñones', price: 28.00, category: 'Tallarines' },
    { code: '1313', name: 'Tallarín con Pollo en Trozos', price: 27.00, category: 'Tallarines' },
    { code: '1314', name: 'Tallarín Frito c/ Pollo en Trozos', price: 32.00, category: 'Tallarines' },
    { code: '1315', name: 'Tallarín con Pollo', price: 27.00, category: 'Tallarines' },
    { code: '1316', name: 'Tallarín Frito con Pollo', price: 30.00, category: 'Tallarines' },
    { code: '1317', name: 'Tallarín Fensi Especial', price: 35.00, category: 'Tallarines' },
    { code: '1318', name: 'Tallarín Fensi con Pollo en Trozos', price: 30.00, category: 'Tallarines' },
    { code: '1319', name: 'Tallarín Fensi Taypa', price: 38.00, category: 'Tallarines' },
    { code: '1320', name: 'Sahofan con Pato', price: 31.00, category: 'Tallarines' },
    { code: '1321', name: 'Sahofan Especial', price: 34.00, category: 'Tallarines' },
    { code: '1322', name: 'Sahofan con Pollo en Trozos', price: 31.00, category: 'Tallarines' },
    { code: '1323', name: 'Sahofan con Carne', price: 32.00, category: 'Tallarines' },
    { code: '1324', name: 'Sahofan con Pollo en Trozos y Huevito de Codorniz', price: 38.00, category: 'Tallarines' },
    { code: '1325', name: 'Porción de Tallarín', price: 9.00, category: 'Tallarines' },
    // Combinados
    { code: '1420', name: 'Combinado con Pollo', price: 29.00, category: 'Combinados' },
    { code: '1421', name: 'Combinado con Chancho', price: 29.00, category: 'Combinados' },
    { code: '1422', name: 'Combinado c/ Pollo y Champiñones', price: 31.00, category: 'Combinados' },
    { code: '1423', name: 'Combinado con Carne', price: 29.00, category: 'Combinados' },
    { code: '1424', name: 'Combinado Especial', price: 32.00, category: 'Combinados' },
    { code: '1425', name: 'Combinado con Pollo en Trozos', price: 29.00, category: 'Combinados' },
    { code: '1426', name: 'Aeropuerto Taypa', price: 32.00, category: 'Combinados' },
    { code: '1493', name: 'Aeropuerto de pollo', price: 29.00, category: 'Combinados' },
    { code: '1494', name: 'Aeropuerto de chancho', price: 29.00, category: 'Combinados' },
    { code: '1495', name: 'Aeropuerto de carne', price: 29.00, category: 'Combinados' },
    // Pollo
    { code: '0901', name: 'Chu Pi Kay', price: 35.00, category: 'Pollo' },
    { code: '0902', name: 'Pollo en Sillao', price: 35.00, category: 'Pollo' },
    { code: '0903', name: 'Pollo con Chi Jau Kay', price: 35.00, category: 'Pollo' },
    { code: '0904', name: 'Pollo Enrollado con Espárragos', price: 31.00, category: 'Pollo' },
    { code: '0905', name: 'Pollo Enrollado con Salsa Blanca', price: 32.00, category: 'Pollo' },
    { code: '0906', name: 'Pollo Enrollado con Piña (Dulce)', price: 32.00, category: 'Pollo' },
    { code: '0907', name: 'Limon Kay (Agridulce)', price: 31.00, category: 'Pollo' },
    { code: '0908', name: 'Pollo en Trozos con Champiñones', price: 31.00, category: 'Pollo' },
    { code: '0909', name: 'Pollo en Trozos con Hongo', price: 32.00, category: 'Pollo' },
    { code: '0910', name: 'Pollo en Trozos con Verduras', price: 30.00, category: 'Pollo' },
    { code: '0911', name: 'Pollo en Trozos c/ Tausí', price: 31.00, category: 'Pollo' },
    { code: '0912', name: 'Pollo en Trozos c/ Verduras y Tausí', price: 31.00, category: 'Pollo' },
    { code: '0913', name: 'Pollo en Trozos c/ Verduras y Huevitos', price: 33.00, category: 'Pollo' },
    { code: '0914', name: 'Pollo Tipakay (Dulce)', price: 31.00, category: 'Pollo' },
    { code: '0915', name: 'Pollo al Ajo', price: 32.00, category: 'Pollo' },
    { code: '0916', name: 'Pollo en Trozos con Piña (Dulce)', price: 31.00, category: 'Pollo' },
    { code: '0917', name: 'Pollo en Trozos c/ Durazno (Dulce)', price: 30.00, category: 'Pollo' },
    { code: '0918', name: 'Pollo Cinco Sabores (Dulce)', price: 31.00, category: 'Pollo' },
    { code: '0919', name: 'Pollo con Frejolito', price: 31.00, category: 'Pollo' },
    { code: '0973', name: 'Chijaukay (02 sabores)', price: 35.00, category: 'Pollo' },
    // Carne de Res
    { code: '1101', name: 'Carne de Res c/ Champiñones', price: 38.00, category: 'Carne de Res' },
    { code: '1102', name: 'Carne de Res c/ Bambú con y Tausí', price: 38.00, category: 'Carne de Res' },
    { code: '1103', name: 'Carne de Res con Verdura', price: 31.00, category: 'Carne de Res' },
    { code: '1104', name: 'Lomo Saltado con Carne', price: 32.00, category: 'Carne de Res' },
    { code: '1105', name: 'Lomo Saltado con Chancho', price: 32.00, category: 'Carne de Res' },
    { code: '1106', name: 'Lomo Saltado Especial', price: 35.00, category: 'Carne de Res' },
    { code: '1107', name: 'Carne con Frejolitos', price: 33.00, category: 'Carne de Res' },
    // Verduras
    { code: '1701', name: 'Taufú con Hongos Chinos', price: 30.00, category: 'Verduras' },
    { code: '1702', name: 'Hongos Chinos', price: 41.00, category: 'Verduras' },
    { code: 'V001', name: 'Champiñones y Yuyo', price: 0.00, category: 'Verduras' },
    { code: 'V002', name: 'Saltado con Verduras', price: 0.00, category: 'Verduras' },
    // Arroz Chaufa
    { code: '1401', name: 'Arroz Chaufa c/ Pollo', price: 25.00, category: 'Arroz Chaufa',
      description: 'El plato insignia del Chifa. Arroz salteado a fuego alto en wok con trozos de pollo, tortilla de huevo en trocitos, pimiento y cebolla china, todo unido con el inconfundible sabor del sillao.',
      ingredients: ['Arroz', 'Pollo', 'Huevo', 'Sillao (Salsa de soja)', 'Cebolla china', 'Pimiento', 'Aceite de sésamo']
    },
    { code: '1402', name: 'Arroz Chaufa c/ Chancho Asado', price: 28.00, category: 'Arroz Chaufa' },
    { code: '1403', name: 'Arroz Chaufa c/ Langostinos', price: 29.00, category: 'Arroz Chaufa' },
    { code: '1404', name: 'Arroz Chaufa c/ Pollo y Chancho As.', price: 28.00, category: 'Arroz Chaufa' },
    { code: '1405', name: 'Arroz Chaufa c/ Carne de Res', price: 27.00, category: 'Arroz Chaufa' },
    { code: '1406', name: 'Arroz Chaufa c/ Salchicha China', price: 35.00, category: 'Arroz Chaufa' },
    { code: '1407', name: 'Arroz Chaufa c/ Champiñones', price: 29.00, category: 'Arroz Chaufa' },
    { code: '1408', name: 'Arroz Chaufa c/ Verduras', price: 23.00, category: 'Arroz Chaufa' },
    { code: '1409', name: 'Arroz Chaufa Especial', price: 28.00, category: 'Arroz Chaufa' },
    { code: '1410', name: 'Arroz Chaufa c/ Pollo y Champ.', price: 29.00, category: 'Arroz Chaufa' },
    { code: '1411', name: 'Arroz Chaufa c/ Pollo y Verduras', price: 27.00, category: 'Arroz Chaufa' },
    { code: '1412', name: 'Arroz Chaufa c/ Pollo en Trozos', price: 29.00, category: 'Arroz Chaufa' },
    { code: '1413', name: 'Arroz Chaufa con Pato', price: 30.00, category: 'Arroz Chaufa' },
    { code: '1414', name: 'Arroz Chaufa con Piña', price: 28.00, category: 'Arroz Chaufa' },
    { code: '1415', name: 'Arroz Taypá Especial', price: 34.00, category: 'Arroz Chaufa' },
    { code: '1416', name: 'Arroz Chaufa con Tausí', price: 28.00, category: 'Arroz Chaufa' },
    { code: '1417', name: 'Porción de Chaufa con Pollo', price: 18.00, category: 'Arroz Chaufa' },
    { code: '1418', name: 'Porción de Chaufa con Chancho', price: 18.00, category: 'Arroz Chaufa' },
    { code: '1419', name: 'Porción de Arroz Blanco', price: 10.00, category: 'Arroz Chaufa' },
    // Platos a la Plancha
    { code: '2101', name: 'Taypá Especial a la Plancha', price: 44.00, category: 'Platos a la Plancha' },
    { code: '2102', name: 'Pollo con Tausí a la Plancha', price: 38.00, category: 'Platos a la Plancha' },
    { code: '2103', name: 'Carne de Res con Tausí a la Plancha', price: 39.00, category: 'Platos a la Plancha' },
    // Pato
    { code: '1001', name: 'Pato Asado 1/2', price: 69.00, category: 'Pato' },
    { code: '1002', name: 'Pato Asado 1/4', price: 42.00, category: 'Pato' },
    { code: '1003', name: 'Pato con Verduras', price: 70.00, category: 'Pato' },
    // Platos Especiales
    { code: '0301', name: 'Kam Pao Kay Tiam (spicy)', price: 35.00, category: 'Platos Especiales' },
    { code: '0302', name: 'Kay Tiam Especial', price: 37.00, category: 'Platos Especiales' },
    { code: '0303', name: 'Kamlú Wantán', price: 37.00, category: 'Platos Especiales' },
    { code: '0304', name: 'Kay Tiam con Almendra', price: 39.00, category: 'Platos Especiales' },
    { code: '0305', name: 'Pi Pa Kay (spicy)', price: 39.00, category: 'Platos Especiales' },
    { code: '0306', name: 'Mapo Taufu (spicy)', price: 30.00, category: 'Platos Especiales' },
    { code: '0307', name: 'Sam Kay', price: 37.00, category: 'Platos Especiales' },
    { code: '0308', name: 'Pollo c/ Hongos y Huevito de Codorniz', price: 32.00, category: 'Platos Especiales' },
    { code: '0309', name: 'Pano Kay Poy con Piña Y Durazno', price: 32.00, category: 'Platos Especiales' },
    { code: '0310', name: 'Paa Kin Chong Long', price: 35.00, category: 'Platos Especiales' },
    // Tortilla
    { code: '2201', name: 'Tortilla con Verduras', price: 25.00, category: 'Tortilla' },
    { code: '2202', name: 'Tortilla de Pollo y Verduras', price: 28.00, category: 'Tortilla' },
    { code: '2203', name: 'Tortilla de Langostinos', price: 33.00, category: 'Tortilla' },
    { code: '2204', name: 'Tortilla de Champiñones y Pollo', price: 31.00, category: 'Tortilla' },
    // Mariscos
    { code: '0801', name: 'Langostino con Almendra al nido special', price: 48.00, category: 'Mariscos' },
    { code: '0802', name: 'Langostino c/ Champiñones y Verduras', price: 52.00, category: 'Mariscos' },
    { code: '0803', name: 'Langostino con Tausí y Verduras', price: 52.00, category: 'Mariscos' },
    { code: '0804', name: 'Tortilla de Huevo con Nabo', price: 52.00, category: 'Mariscos' },
    { code: '0805', name: 'Pescado con Taufú y Verduras', price: 48.00, category: 'Mariscos' },
    { code: '0806', name: 'Pescado c/ Hongo Chino y Verduras', price: 48.00, category: 'Mariscos' },
    { code: '0807', name: 'Pescado con Frutas (Dulce)', price: 42.00, category: 'Mariscos' },
    // Chancho
    { code: '1201', name: 'Chancho Asado c/ Ver. y Champ.', price: 32.00, category: 'Chancho' },
    { code: '1202', name: 'Chancho Asado con Verduras', price: 31.00, category: 'Chancho' },
    { code: '1203', name: 'Chancho Asado con Frejolito', price: 32.00, category: 'Chancho' },
    { code: '1204', name: 'Chancho Asado c/ Tausí y Ver.', price: 32.00, category: 'Chancho' },
    { code: '1205', name: 'Chancho Asado al Ajo', price: 34.00, category: 'Chancho' },
    { code: '1206', name: 'Chancho Asado c/ Tamarindo (Dulce)', price: 31.00, category: 'Chancho' },
    { code: '1207', name: 'Chancho Asado con Piña (Dulce)', price: 31.00, category: 'Chancho' },
    { code: '1208', name: 'Chancho Cinco Sabores', price: 32.00, category: 'Chancho' },
    { code: '1209', name: 'Chancho Asado c/ Durazno (Dulce)', price: 35.00, category: 'Chancho' },
];

export const menuData: Dish[] = originalMenuData.map(transformCombo);